const esc = (value = "") =>
  String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        character
      ],
  );
const widgetTitle = (icon, label) =>
  `<div class="widget-heading"><span aria-hidden="true">${icon}</span><p>${label}</p><span class="widget-grip" aria-hidden="true">⠿</span></div>`;
const drag = (name, id) =>
  `data-playground-card data-widget-id="${id}" tabindex="0" aria-label="${name} widget. Arrow keys move this widget."`;

export function renderPlayground({ profile = {} } = {}) {
  return `<h1 class="sr-only" id="playground-title">Play Lab</h1><nav class="play-lab-switch" aria-label="Play Lab sections" role="tablist"><a href="#canvas" id="canvas-tab" role="tab" aria-controls="canvas" aria-selected="true" aria-current="location">Canvas</a><a href="#interactions" id="interactions-tab" role="tab" aria-controls="interactions" aria-selected="false" tabindex="-1">Interactions</a></nav>
  <section class="playground-section" id="canvas" role="tabpanel" aria-labelledby="canvas-tab" tabindex="0">
    <div class="playground-board" data-playground-board aria-describedby="playground-instructions" tabindex="0" aria-label="Interactive canvas. Drag empty space to pan. Scroll to zoom. Use arrow keys here to pan, or focus a card to move it.">
      <div class="playground-pin-tray" role="group" aria-label="Pin a card" hidden>${["gold", "teal", "violet"].map(color => `<button type="button" class="playground-pin-tool" data-pin-colour="${color}" aria-label="${color} pin: drag onto a card, or select and then choose a card" aria-pressed="false"><span aria-hidden="true"></span></button>`).join("")}</div>
      <button class="playground-view" type="button" data-playground-view aria-pressed="false" hidden>List view</button>
      <div class="playground-world">
        <article class="playground-card playground-note" ${drag("Sticky note", "note")}>${widgetTitle("✎", "A little thought")}<label class="sr-only" for="playground-note">Your sticky note</label><textarea id="playground-note" data-widget-note maxlength="240" spellcheck="true">What if we made something useful… and a little delightful?</textarea><div class="widget-note-bottom"><span>Yours to edit.</span><span data-widget-note-count>0 / 240</span></div><span class="playground-signature">— ${esc((profile.name || "Baivab Sarkar").split(" ")[0])}</span></article>
        <article class="playground-card playground-focus" ${drag("Focus timer", "focus")}>${widgetTitle("◷", "A moment of focus")}<div class="widget-timer-ring"><output data-widget-timer aria-label="Time remaining">05:00</output><span>one thing at a time</span></div><div class="widget-timer-presets" role="group" aria-label="Timer duration"><button type="button" data-widget-duration="5" aria-pressed="true">5 min</button><button type="button" data-widget-duration="15" aria-pressed="false">15 min</button><button type="button" data-widget-duration="25" aria-pressed="false">25 min</button></div><div class="widget-timer-actions"><button type="button" data-widget-timer-toggle>Start focus</button><button type="button" data-widget-timer-reset aria-label="Reset focus timer">↺</button></div><p class="sr-only" role="status" data-widget-timer-status></p></article>
        <article class="playground-card playground-clock" ${drag("Local time in West Bengal", "clock")}>${widgetTitle("◉", "On my side of the world")}<span class="playground-clock-face" aria-hidden="true"><i class="playground-clock-hour"></i><i class="playground-clock-minute"></i><b></b></span><p>West Bengal, India</p><time data-playground-time>UTC +05:30</time><small>Somewhere between ideas & commits.</small></article>
        <article class="playground-card playground-todo" ${drag("Checklist", "tasks")}>${widgetTitle("✓", "Little wins")}<h2>Good things<br>take small steps.</h2><label><input type="checkbox" data-playground-check="explore"><span>Explore a project</span></label><label><input type="checkbox" data-playground-check="read"><span>Read something new</span></label><label><input type="checkbox" data-playground-check="hello"><span>Say hello</span></label><div class="widget-task-progress" aria-hidden="true"><span data-widget-task-progress></span></div><p class="widget-completion" data-widget-task-count>0 of 3 little wins</p></article>
        <article class="playground-card playground-vote" ${drag("Idea vote", "vote")}>${widgetTitle("✳", "You have a vote")}<h2>What should I<br>build next?</h2><div class="widget-vote-options" role="group" aria-label="Choose your favourite project idea"><button type="button" data-widget-vote="tool" aria-pressed="false"><span>A useful little tool</span><b aria-hidden="true">↗</b></button><button type="button" data-widget-vote="experiment" aria-pressed="false"><span>A playful experiment</span><b aria-hidden="true">✦</b></button><button type="button" data-widget-vote="article" aria-pressed="false"><span>A deep technical read</span><b aria-hidden="true">≡</b></button></div><p data-widget-vote-status role="status">Just for fun. Your pick stays in this browser.</p></article>
        <article class="playground-card playground-mixer" ${drag("Palette mixer", "mixer")}>${widgetTitle("◒", "Make a little colour")}<div class="widget-colour-preview" data-widget-colour-preview><span>Good things<br>come in colour.</span><output data-widget-colour-code>#D1C2F0</output></div><label for="widget-hue">Find your hue <output data-widget-hue>260°</output></label><input id="widget-hue" type="range" min="0" max="359" value="260" data-widget-hue-input><button class="widget-copy" type="button" data-widget-colour-copy>Copy colour <span aria-hidden="true">⧉</span></button><p class="sr-only" role="status" data-widget-colour-status></p></article>
        <article class="playground-card playground-work" ${drag("Currently building", "project")}>${widgetTitle("↗", "From idea to browser")}<img src="/assets/work/markdown-viewer-800.webp" alt="Markdown Viewer editor and rendered preview" width="800" height="450" loading="lazy"><h2>Markdown Viewer</h2><p>A calmer place to write, preview, and share.</p><a href="/work/markdown-viewer">Explore the project <span aria-hidden="true">↗</span></a></article>
      </div>
      <div class="playground-palette" role="group" aria-label="Canvas background" hidden>${["pink", "peach", "cream", "green", "blue", "lilac"].map((color) => `<button class="playground-swatch playground-swatch-${color}" type="button" data-playground-color="${color}" aria-label="${color[0].toUpperCase() + color.slice(1)} canvas" aria-pressed="${color === "blue"}"></button>`).join("")}<button class="playground-background-reset" type="button" data-playground-background-reset aria-label="Reset canvas background">↺</button></div>
      <div class="playground-canvas-hint" id="playground-instructions"><span aria-hidden="true">↕</span> Drag to pan <span aria-hidden="true">·</span> Scroll to zoom</div>
      <div class="playground-controls" role="group" aria-label="Canvas controls" hidden><button type="button" data-playground-zoom="in" aria-label="Zoom in">+</button><button type="button" data-playground-zoom="out" aria-label="Zoom out">−</button><button type="button" data-playground-reset aria-label="Reset canvas positions and zoom">↻</button><output class="sr-only" data-playground-zoom-label aria-label="Canvas zoom">100%</output></div>
    </div>
    <p class="playground-help sr-only">Grab a card and give it a little throw. Drag the empty canvas to explore. Scroll over it to zoom at your pointer; zoom out for more room. Arrow keys move a focused card or pan the canvas. Buttons and inputs work as usual.</p><p class="sr-only" role="status" data-playground-status></p>
  </section>${renderInteractions()}`;
}

export function renderInteractions() {
  return `<section class="playground-interactions" id="interactions" role="tabpanel" aria-labelledby="interactions-tab" tabindex="0"><h2 class="sr-only" id="interactions-title">Interaction experiments</h2>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-shape-stage"><div class="interaction-shape" data-interaction-shape="flower" aria-hidden="true"><span>✳</span></div><div class="interaction-choice" role="group" aria-label="Choose a shape">${["flower", "circle", "square", "star"].map((shape) => `<button type="button" data-shape-choice="${shape}" aria-pressed="${shape === "flower"}">${shape[0].toUpperCase() + shape.slice(1)}</button>`).join("")}</div><p class="sr-only" role="status" data-shape-status></p></div><div class="playground-experiment-caption"><span>01 / FORM</span><h3>A change of shape</h3><p>One form, four personalities. Pick your favourite.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-spring-stage"><div class="interaction-spring-track"><button class="interaction-spring-ball" type="button" aria-label="Spring ball. Drag and release, or use the arrow keys to move it." data-spring-ball></button><i aria-hidden="true"></i><i aria-hidden="true"></i><i aria-hidden="true"></i></div><div class="interaction-choice" role="group" aria-label="Spring character"><button type="button" data-spring-character="soft" aria-pressed="false">Soft</button><button type="button" data-spring-character="snappy" aria-pressed="true">Snappy</button><button type="button" data-spring-character="bouncy" aria-pressed="false">Bouncy</button></div><button class="interaction-primary" type="button" data-spring-launch>Give it a nudge <span aria-hidden="true">↗</span></button><p class="sr-only" role="status" data-spring-status></p></div><div class="playground-experiment-caption"><span>02 / PHYSICS</span><h3>Just the right bounce</h3><p>Pull, let go, and find the spring that feels right.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-depth-stage"><button class="interaction-depth-card" type="button" aria-pressed="false" data-depth-card aria-describedby="depth-instructions"><span class="depth-card-front"><span class="depth-card-top">THE LITTLE STUDIO <span aria-hidden="true">✳</span></span><strong>Stay<br><em>curious.</em></strong><span class="depth-card-bottom">BAIVAB SARKAR <span>01 — ∞</span></span></span><span class="depth-card-back" hidden><span aria-hidden="true">✳</span><strong>Good ideas<br>start with<br>a little play.</strong><small>Keep making things.</small></span></button><p id="depth-instructions">Move around it. Tap to turn it over.</p></div><div class="playground-experiment-caption"><span>03 / DEPTH</span><h3>A different perspective</h3><p>A little depth on hover, a new thought on the other side.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-joy-stage"><div class="interaction-joy-halo" aria-hidden="true"></div><div class="interaction-joy-orbit" aria-hidden="true">${Array.from({ length: 18 }, (_, i) => `<span>${["✳", "✦", "●"][i % 3]}</span>`).join("")}</div><button class="interaction-joy-button" type="button" data-joy-button><span aria-hidden="true">✦</span><strong>A little joy</strong></button><p data-joy-status role="status">Go on. Make someone's day. Yours counts.</p></div><div class="playground-experiment-caption"><span>04 / FEEDBACK</span><h3>A good click goes a long way</h3><p>A full burst of colour, because small things count.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-bloom-stage"><div class="interaction-bloom" data-bloom aria-hidden="true">${Array.from({ length: 8 }, (_, i) => `<i class="bloom-petal-${i}"></i>`).join("")}<span>✳</span></div><div class="interaction-bloom-control"><label for="bloom-spread">Room to bloom <output data-bloom-value>60%</output></label><input type="range" id="bloom-spread" min="0" max="100" value="60" data-bloom-spread></div><button class="interaction-primary" type="button" data-bloom-spin>Give it a spin <span aria-hidden="true">↻</span></button><p class="sr-only" role="status" data-bloom-status></p></div><div class="playground-experiment-caption"><span>05 / PLAYFUL GEOMETRY</span><h3>Make room for a little wonder</h3><p>Open the petals. Follow your pointer. Find your own rhythm.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-ripple-stage" data-ripple-theme="sky"><button class="interaction-ripple-pond" type="button" data-ripple-pond aria-label="Make a ripple in the water" aria-describedby="ripple-instructions"><canvas class="ripple-water" data-ripple-water aria-hidden="true"></canvas><span class="ripple-decoration" aria-hidden="true"><i></i><i></i><i></i></span><span class="ripple-center"><span aria-hidden="true">◌</span><strong>Make a ripple</strong></span></button><div class="interaction-choice" role="group" aria-label="Ripple colour">${["sky", "mint", "rose"].map((theme) => `<button type="button" data-ripple-colour="${theme}" aria-pressed="${theme === "sky"}">${theme[0].toUpperCase() + theme.slice(1)}</button>`).join("")}</div><p id="ripple-instructions" data-ripple-status role="status">Tap the water. See where a small thing goes.</p></div><div class="playground-experiment-caption"><span>06 / RIPPLE EFFECT</span><h3>Small touch. Lovely possibilities.</h3><p>A quiet pond, a changing palette, and a ripple of your own.</p></div></article>
  </section>`;
}
