const esc = (value = "") => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
const widgetTitle = (icon, label) => `<div class="widget-heading"><span aria-hidden="true">${icon}</span><p>${label}</p><span class="widget-grip" aria-hidden="true">⠿</span></div>`;
const drag = (name, id) => `data-playground-card data-widget-id="${id}" tabindex="0" aria-label="${name} widget. Arrow keys move this widget."`;

export function renderPlayground({ profile = {} } = {}) {
  return `<section class="playground-intro sr-only" aria-labelledby="playground-title"><h1 id="playground-title">A canvas for curious minds.</h1></section>
  <section class="playground-section" aria-label="Interactive personal canvas">
    <div class="playground-topline"><div><span class="playground-live" aria-hidden="true"></span><strong>The little idea board</strong><p id="playground-instructions">Move things around. Leave a little thought.</p></div><button class="playground-view" type="button" data-playground-view aria-pressed="false" hidden>List view</button></div>
    <div class="playground-board" data-playground-board aria-describedby="playground-instructions">
      <div class="playground-world">
        <article class="playground-card playground-note" ${drag("Sticky note", "note")}>${widgetTitle("✎", "A little thought")}<label class="sr-only" for="playground-note">Your sticky note</label><textarea id="playground-note" data-widget-note maxlength="240" spellcheck="true">What if we made something useful… and a little delightful?</textarea><div class="widget-note-bottom"><span>Yours to edit.</span><span data-widget-note-count>0 / 240</span></div><span class="playground-signature">— ${esc((profile.name || "Baivab Sarkar").split(" ")[0])}</span></article>
        <article class="playground-card playground-focus" ${drag("Focus timer", "focus")}>${widgetTitle("◷", "A moment of focus")}<div class="widget-timer-ring"><output data-widget-timer aria-label="Time remaining">05:00</output><span>one thing at a time</span></div><div class="widget-timer-presets" role="group" aria-label="Timer duration"><button type="button" data-widget-duration="5" aria-pressed="true">5 min</button><button type="button" data-widget-duration="15" aria-pressed="false">15 min</button><button type="button" data-widget-duration="25" aria-pressed="false">25 min</button></div><div class="widget-timer-actions"><button type="button" data-widget-timer-toggle>Start focus</button><button type="button" data-widget-timer-reset aria-label="Reset focus timer">↺</button></div><p class="sr-only" role="status" data-widget-timer-status></p></article>
        <article class="playground-card playground-clock" ${drag("Local time in West Bengal", "clock")}>${widgetTitle("◉", "On my side of the world")}<span class="playground-clock-face" aria-hidden="true"><i class="playground-clock-hour"></i><i class="playground-clock-minute"></i><b></b></span><p>West Bengal, India</p><time data-playground-time>UTC +05:30</time><small>Somewhere between ideas & commits.</small></article>
        <article class="playground-card playground-todo" ${drag("Checklist", "tasks")}>${widgetTitle("✓", "Little wins")}<h2>Good things<br>take small steps.</h2><label><input type="checkbox" data-playground-check="explore"><span>Explore a project</span></label><label><input type="checkbox" data-playground-check="read"><span>Read something new</span></label><label><input type="checkbox" data-playground-check="hello"><span>Say hello</span></label><div class="widget-task-progress" aria-hidden="true"><span data-widget-task-progress></span></div><p class="widget-completion" data-widget-task-count>0 of 3 little wins</p></article>
        <article class="playground-card playground-vote" ${drag("Idea vote", "vote")}>${widgetTitle("✳", "You have a vote")}<h2>What should I<br>build next?</h2><div class="widget-vote-options" role="group" aria-label="Choose your favourite project idea"><button type="button" data-widget-vote="tool" aria-pressed="false"><span>A useful little tool</span><b aria-hidden="true">↗</b></button><button type="button" data-widget-vote="experiment" aria-pressed="false"><span>A playful experiment</span><b aria-hidden="true">✦</b></button><button type="button" data-widget-vote="article" aria-pressed="false"><span>A deep technical read</span><b aria-hidden="true">≡</b></button></div><p data-widget-vote-status role="status">Just for fun. Your pick stays in this browser.</p></article>
        <article class="playground-card playground-mixer" ${drag("Palette mixer", "mixer")}>${widgetTitle("◒", "Make a little colour")}<div class="widget-colour-preview" data-widget-colour-preview><span>Good things<br>come in colour.</span><output data-widget-colour-code>#D1C2F0</output></div><label for="widget-hue">Find your hue <output data-widget-hue>260°</output></label><input id="widget-hue" type="range" min="0" max="359" value="260" data-widget-hue-input><button class="widget-copy" type="button" data-widget-colour-copy>Copy colour <span aria-hidden="true">⧉</span></button><p class="sr-only" role="status" data-widget-colour-status></p></article>
        <article class="playground-card playground-work" ${drag("Currently building", "project")}>${widgetTitle("↗", "From idea to browser")}<img src="/assets/work/markdown-viewer-800.webp" alt="Markdown Viewer editor and rendered preview" width="800" height="450" loading="lazy"><h2>Markdown Viewer</h2><p>A calmer place to write, preview, and share.</p><a href="/work/markdown-viewer">Explore the project <span aria-hidden="true">↗</span></a></article>
      </div>
      <div class="playground-palette" role="group" aria-label="Canvas background" hidden>${["blue", "cream", "green", "lilac", "pink"].map((color) => `<button class="playground-swatch playground-swatch-${color}" type="button" data-playground-color="${color}" aria-label="${color[0].toUpperCase() + color.slice(1)} canvas" aria-pressed="${color === "blue"}"></button>`).join("")}</div>
      <div class="playground-controls" role="group" aria-label="Canvas controls" hidden><button type="button" data-playground-zoom="out" aria-label="Zoom out">−</button><output data-playground-zoom-label aria-label="Canvas zoom">100%</output><button type="button" data-playground-zoom="in" aria-label="Zoom in">+</button><button type="button" data-playground-reset aria-label="Reset canvas positions and zoom">↺</button></div>
    </div>
    <p class="playground-help">Drag a widget by its heading, or focus it and use the arrow keys. Notes, picks, colours and checklists stay in this browser.</p><p class="sr-only" role="status" data-playground-status></p>
  </section>`;
}

export function renderInteractions() {
  return `<section class="playground-intro playground-interactions-intro" aria-labelledby="interactions-title"><nav class="view-switch" aria-label="Work views"><a href="/work">Work</a><a href="/interactions" aria-current="page">Interactions</a></nav><p class="eyebrow">SMALL DETAILS. A LITTLE DELIGHT.</p><h1 id="interactions-title">Made to be <em>played with.</em></h1><p>Six little studies in motion, feedback, and feel.</p></section>
  <section class="playground-interactions" aria-label="Interaction experiments">
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-shape-stage"><div class="interaction-shape" data-interaction-shape="flower" aria-hidden="true"><span>✳</span></div><div class="interaction-choice" role="group" aria-label="Choose a shape">${["flower", "circle", "square", "star"].map((shape) => `<button type="button" data-shape-choice="${shape}" aria-pressed="${shape === "flower"}">${shape[0].toUpperCase() + shape.slice(1)}</button>`).join("")}</div><p class="sr-only" role="status" data-shape-status></p></div><div class="playground-experiment-caption"><span>01 / FORM</span><h2>A change of shape</h2><p>One form, four personalities. Pick your favourite.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-spring-stage"><div class="interaction-spring-track" aria-hidden="true"><span class="interaction-spring-ball"></span><i></i><i></i><i></i></div><div class="interaction-choice" role="group" aria-label="Spring character"><button type="button" data-spring-character="soft" aria-pressed="false">Soft</button><button type="button" data-spring-character="snappy" aria-pressed="true">Snappy</button><button type="button" data-spring-character="bouncy" aria-pressed="false">Bouncy</button></div><button class="interaction-primary" type="button" data-spring-launch>Give it a nudge <span aria-hidden="true">↗</span></button><p class="sr-only" role="status" data-spring-status></p></div><div class="playground-experiment-caption"><span>02 / PHYSICS</span><h2>Just the right bounce</h2><p>Same distance. A completely different feeling.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-depth-stage"><button class="interaction-depth-card" type="button" aria-pressed="false" data-depth-card aria-describedby="depth-instructions"><span class="depth-card-front"><span class="depth-card-top">THE LITTLE STUDIO <span aria-hidden="true">✳</span></span><strong>Stay<br><em>curious.</em></strong><span class="depth-card-bottom">BAIVAB SARKAR <span>01 — ∞</span></span></span><span class="depth-card-back" hidden><span aria-hidden="true">✳</span><strong>Good ideas<br>start with<br>a little play.</strong><small>Keep making things.</small></span></button><p id="depth-instructions">Move around it. Tap to turn it over.</p></div><div class="playground-experiment-caption"><span>03 / DEPTH</span><h2>A different perspective</h2><p>A little depth on hover, a new thought on the other side.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-joy-stage"><div class="interaction-joy-orbit" aria-hidden="true"><span>✳</span><span>✦</span><span>·</span><span>✳</span><span>✦</span><span>·</span></div><button class="interaction-joy-button" type="button" data-joy-button><span aria-hidden="true">✦</span><strong>A little joy</strong></button><p data-joy-status role="status">Go on. Make someone's day. Yours counts.</p></div><div class="playground-experiment-caption"><span>04 / FEEDBACK</span><h2>A good click goes a long way</h2><p>A tiny celebration, because small things count.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-flow-stage"><div class="interaction-flow" data-flow="idea"><div class="interaction-flow-tabs" role="tablist" aria-label="Creative process"><button type="button" id="flow-idea" data-flow-tab="idea" role="tab" aria-selected="true" aria-controls="flow-panel" tabindex="0">Imagine</button><button type="button" id="flow-build" data-flow-tab="build" role="tab" aria-selected="false" aria-controls="flow-panel" tabindex="-1">Make</button><button type="button" id="flow-ship" data-flow-tab="ship" role="tab" aria-selected="false" aria-controls="flow-panel" tabindex="-1">Share</button></div><div class="interaction-flow-panel" id="flow-panel" role="tabpanel" aria-labelledby="flow-idea" tabindex="0"><span class="interaction-flow-symbol" aria-hidden="true">✳</span><h3 data-flow-title>Start with a what if.</h3><p data-flow-description>A question. A scribble. A possibility worth exploring.</p><span class="interaction-flow-step" data-flow-step>01 / THE SPARK</span></div></div></div><div class="playground-experiment-caption"><span>05 / CONTINUITY</span><h2>One thought leads to another</h2><p>Follow an idea from the first spark to the first hello.</p></div></article>
    <article class="playground-experiment"><div class="playground-experiment-stage interaction-disclosure-stage"><div class="interaction-disclosures"><p class="interaction-disclosure-label">A FEW THINGS I BELIEVE</p><details name="small-beliefs" open><summary>Start with curiosity.<span aria-hidden="true">+</span></summary><p>The best first step is often a better question. Explore before you decide.</p></details><details name="small-beliefs"><summary>Make it useful.<span aria-hidden="true">+</span></summary><p>Good software makes someone's day a little easier. That is a good place to begin.</p></details><details name="small-beliefs"><summary>Leave room for play.<span aria-hidden="true">+</span></summary><p>Try the unexpected thing. Small experiments can lead to surprisingly good ideas.</p></details></div></div><div class="playground-experiment-caption"><span>06 / REVEAL</span><h2>A little room to open up</h2><p>Quiet details that reward a closer look.</p></div></article>
  </section>`;
}
